### ISSUE TITLE
Q2 '19 Roadmap

### ISSUE THREAD

**Issue by cweill** [tensorflow/adanet#101]
In an effort to provide transparency into the work we are doing for the broader open-source community, we will present our roadmaps every month. Please let us know if you have any suggestions as comments.

# Q2 '19

TensorFlow 2.0 Support (#93):

- [ ] Add support for TensorFlow 2.*.
- [x] Drop support for TensorFlow < 1.13 (cb9c718c35b5d16e05b51f15040b4b448798c5d2).

Keras Support (#1):

- [ ] Support `tf.keras.layers`.
- [ ] Support Keras `Sequential` models in `AutoEnsembleEstimator`.
- [ ] Create a Keras Model equivalent of `AutoEnsembleEstimator`.

Better ensembles:

- [x]  `AutoEnsembleEstimator` bagging support: Allow candidates to use different inputs during training. (ebbb7eeda1daa7a3c489c150e1b17ac1c03e7f9c)

Self-Tuning AdaNet:

- [ ] Provide hyperparameter tuning support during architecture search. (More details soon).

**Comment by cweill** [comment]
New roadmap is in #124.
