### ISSUE TITLE
Q3/Q4 '19 Roadmap

### ISSUE THREAD

**Issue by cweill** [tensorflow/adanet#124]
In an effort to provide transparency into the work we are doing for the broader open-source community, we will present our roadmaps every quarter. Please let us know if you have any suggestions as comments.

# Q3/Q4 '19

TensorFlow 2.0 Support (#93):

- [ ] Complete support for TensorFlow 2+ with on-going support for TF 1.14 #93.

Keras Support (#1):

- [ ] Support `tf.keras.layers` #100.
- [ ] Support Keras `Sequential` models in `AutoEnsembleEstimator` #1.
- [ ] Create a Keras Model equivalent of `AutoEnsembleEstimator` #1.

Self-Tuning AdaNet:

- [ ] Provide hyperparameter tuning support during architecture search. (More details soon).

**Comment by bhack** [comment]
Any update on this?
